"""добавили признак публикации

Revision ID: d97d47ef6c42
Revises: 8f138152faf4
Create Date: 2021-04-24 14:30:58.144940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97d47ef6c42'
down_revision = '8f138152faf4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('body_part', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('difficulty', sa.Integer(), nullable=True))
    op.add_column('exercises', sa.Column('equipment', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('img', sa.String(), nullable=True))
    op.add_column('exercises', sa.Column('plot', sa.String(), nullable=True))
    op.drop_column('exercises', 'weight_up')
    op.drop_column('exercises', 'height_down')
    op.drop_column('exercises', 'age_down')
    op.drop_column('exercises', 'height_up')
    op.drop_column('exercises', 'age_up')
    op.drop_column('exercises', 'weight_down')
    op.drop_column('exercises', 'sex')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('sex', sa.VARCHAR(), nullable=True))
    op.add_column('exercises', sa.Column('weight_down', sa.INTEGER(), nullable=True))
    op.add_column('exercises', sa.Column('age_up', sa.INTEGER(), nullable=True))
    op.add_column('exercises', sa.Column('height_up', sa.INTEGER(), nullable=True))
    op.add_column('exercises', sa.Column('age_down', sa.INTEGER(), nullable=True))
    op.add_column('exercises', sa.Column('height_down', sa.INTEGER(), nullable=True))
    op.add_column('exercises', sa.Column('weight_up', sa.INTEGER(), nullable=True))
    op.drop_column('exercises', 'plot')
    op.drop_column('exercises', 'img')
    op.drop_column('exercises', 'equipment')
    op.drop_column('exercises', 'difficulty')
    op.drop_column('exercises', 'body_part')
    # ### end Alembic commands ###
